In [2]:
import pandas as pd 
from sklearn.preprocessing import Binarizer 

# Data Reading

In [4]:
data_set = pd.read_csv( 
        'Data_for_Missing_Values.csv') 
data_set.head(10) 

Country  Age  Salary Purchased
0   France   44   72000        No
1    Spain   17   48000       Yes
2  Germany   30   54000        No
3    Spain   38   61000        No
4  Germany   40   60000       Yes
5   France   15   58000       Yes
6    Spain   30   52000        No
7   France   48   79000       Yes
8  Germany   50   83000        No
9   France   37   67000       Yes

In [5]:
age = data_set.iloc[:, 1].values 
salary = data_set.iloc[:, 2].values 
print ("\nOriginal age data values : \n",  age) 
print ("\nOriginal salary data values : \n",  salary) 


Original age data values : 
 [44 17 30 38 40 15 30 48 50 37]

Original salary data values : 
 [72000 48000 54000 61000 60000 58000 52000 79000 83000 67000]


# Feature Binarization

In [6]:
['Adult' if i>18 else 'Kid' for i in data_set['Age']]

['Adult',
 'Kid',
 'Adult',
 'Adult',
 'Adult',
 'Kid',
 'Adult',
 'Adult',
 'Adult',
 'Adult']

In [7]:
['Taxable' if i>60000 else 'Not Taxable' for i in data_set['Salary']]

['Taxable',
 'Not Taxable',
 'Not Taxable',
 'Taxable',
 'Not Taxable',
 'Not Taxable',
 'Not Taxable',
 'Taxable',
 'Taxable',
 'Taxable']

In [8]:
x = age 
x = x.reshape(1, -1) 
y = salary 
y = y.reshape(1, -1) 
  
# For age, let threshold be 17 
# For salary, let threshold be 60000 
binarizer_1 = Binarizer(18) 
binarizer_2 = Binarizer(60000) 
  
# Transformed feature 
print ("\nBinarized age : \n", binarizer_1.fit_transform(x)) 
  
print ("\nBinarized salary : \n", binarizer_2.fit_transform(y)) 


Binarized age : 
 [[1 0 1 1 1 0 1 1 1 1]]

Binarized salary : 
 [[1 0 0 1 0 0 0 1 1 1]]


C:\Users\mg\anaconda3\lib\site-packages\sklearn\utils\validation.py:68: FutureWarning: Pass threshold=18 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "
C:\Users\mg\anaconda3\lib\site-packages\sklearn\utils\validation.py:68: FutureWarning: Pass threshold=60000 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


# K-Bins-Discretization

In [12]:
print(data_set['Age'])
print(pd.qcut(data_set['Age'], 3, labels=False))

0    44
1    17
2    30
3    38
4    40
5    15
6    30
7    48
8    50
9    37
Name: Age, dtype: int64
0    2
1    0
2    0
3    1
4    1
5    0
6    0
7    2
8    2
9    1
Name: Age, dtype: int64
